/* ============================================
   LEADERBOARD - SESSION + SCORE PREVIEW
   ============================================ */
const Leaderboard={
    criteria:['Teaching Effectiveness','Subject Knowledge','Communication Skills','Research & Academic Contribution','Committee Participation','Departmental Service','Training & Workshops'],
    init(){if(!App.checkAuth())return;if(App.isLecturer()){window.location.href='dashboard.html';return;}this.setupSessionFilter();this.setupDepartmentFilter();this.setupPreviewModal();this.renderLeaderboard();},
    sessions(){return App.getSessions().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));},
    selectedSessionId(){return document.getElementById('leaderboardSession')?.value||App.getActiveSession()?.id||this.sessions()[0]?.id||'';},
    getData(dept=''){
        const evals=JSON.parse(localStorage.getItem('evaluations'))||[],users=App.getUsers(),u=App.getCurrentUser(),sid=this.selectedSessionId();
        let filteredEvals = evals.filter(e=>e.sessionId===sid && e.evaluatorRole==='Student');
        if(u.role==='HOD') filteredEvals = filteredEvals.filter(e=>e.department===u.department);
        if(dept) filteredEvals = filteredEvals.filter(e=>e.department===dept);
        const grouped = {};
        filteredEvals.forEach(e => {
            if(!grouped[e.staffId]) grouped[e.staffId] = { ...e, evalsCount: 0, totalScoreSum: 0 };
            grouped[e.staffId].evalsCount++;
            grouped[e.staffId].totalScoreSum += (e.totalScore||0);
        });
        const reviews = JSON.parse(localStorage.getItem('hodReviews'))||[];
        let data = Object.values(grouped).map(g => {
            const staff=users.find(x=>x.id===g.staffId);
            const review = reviews.find(r => r.staffId === g.staffId && r.sessionId === sid);
            return { ...g, name:staff?.fullName||'Unknown', staffIdNumber:staff?.staffId||'N/A', totalScore: Math.round(g.totalScoreSum / g.evalsCount), hodReview: review };
        });
        return data.sort((a,b)=>(b.totalScore||0)-(a.totalScore||0));
    },
    renderLeaderboard(dept=''){const c=document.getElementById('leaderboardContainer'),empty=document.getElementById('leaderboardEmpty'),data=this.getData(dept);if(!data.length){c.innerHTML='';empty.classList.remove('hidden');return;}empty.classList.add('hidden');c.innerHTML=data.map((e,i)=>{const r=i+1,cl=r===1?'gold':r===2?'silver':r===3?'bronze':'other';return `<div class="leaderboard-item"><div class="leaderboard-rank ${cl}">${r}</div><div class="leaderboard-info"><h4>${e.name}</h4><p>${e.department} • ${e.sessionName||'Session'}</p><small class="text-${e.hodReview ? 'success' : 'warning'}">${e.hodReview ? '<i class="bi bi-check-circle-fill"></i> Reviewed by HOD' : 'Pending HOD Review'}</small></div><div class="leaderboard-score"><h3>${e.totalScore||0}%</h3><p>${App.formatDate(e.date)}</p></div><button class="btn btn-sm btn-outline-primary leaderboard-preview-btn" data-staffid="${e.staffId}"><i class="bi bi-eye"></i> Preview</button></div>`;}).join('');c.querySelectorAll('.leaderboard-preview-btn').forEach(b=>b.onclick=()=>this.preview(b.dataset.staffid));},
    setupSessionFilter(){const f=document.getElementById('leaderboardSession');if(!f)return;const ss=this.sessions();f.innerHTML=ss.length?ss.map(s=>`<option value="${s.id}">${s.name}${s.status==='Open'?' • OPEN':''}</option>`).join(''):'<option value="">No sessions</option>';const active=App.getActiveSession();if(active)f.value=active.id;f.addEventListener('change',()=>this.renderLeaderboard(document.getElementById('leaderboardFilter').value));},
    setupDepartmentFilter(){const f=document.getElementById('leaderboardFilter'),u=App.getCurrentUser();if(!f)return;if(u.role==='VC'){App.getDepartments().forEach(d=>f.insertAdjacentHTML('beforeend',`<option value="${d}">${d}</option>`));}else f.style.display='none';f.addEventListener('change',()=>this.renderLeaderboard(f.value));},
    setupPreviewModal(){document.getElementById('closeLeaderboardPreview')?.addEventListener('click',()=>document.getElementById('leaderboardPreviewModal').classList.remove('active'));},
    async preview(staffId){const sid=this.selectedSessionId(),evals=(JSON.parse(localStorage.getItem('evaluations'))||[]).filter(x=>x.staffId===staffId&&x.sessionId===sid&&x.evaluatorRole==='Student');if(!evals.length)return;const e=evals[0],users=App.getUsers(),staff=users.find(u=>u.id===staffId),avgScore=Math.round(evals.reduce((s,ev)=>s+(ev.totalScore||0),0)/evals.length),review=(JSON.parse(localStorage.getItem('hodReviews'))||[]).find(r=>r.staffId===staffId&&r.sessionId===sid);document.getElementById('leaderboardPreviewTitle').textContent=`${staff?.fullName||'Staff'} — ${e.sessionName||'Appraisal'}`;const apps=(JSON.parse(localStorage.getItem('applications'))||[]).filter(a=>a.staffId===staffId&&a.sessionId===sid),certs=apps.flatMap(a=>a.certificates||[]);document.getElementById('leaderboardPreviewBody').innerHTML=`<div class="preview-meta"><span><strong>Staff ID</strong>${staff?.staffId||'N/A'}</span><span><strong>Department</strong>${e.department}</span><span><strong>Student Evals</strong>${evals.length}</span><span><strong>Total Avg Score</strong>${avgScore}%</span></div><div class="mt-3"><h5>HOD Review</h5><div class="app-details-box">${review?`<strong>Recommendation:</strong> ${review.recommendation}<br><br><strong>Comments:</strong><br>${review.comments||'None'}`:'<span class="text-gray">Pending HOD Review</span>'}</div></div><div class="mt-3"><h5>Uploaded Certificate / Documents</h5>${certs.length?`<div class="cert-preview-list">${certs.map((c,i)=>`<button class="cert-preview-item" type="button" onclick="Leaderboard.previewDocument(${JSON.stringify(c).replace(/"/g,'&quot;')})"><i class="bi ${App.fileIcon(c.name)}"></i><span class="cert-preview-name">${c.name}</span><span class="cert-preview-badge"><i class="bi bi-eye"></i> View</span></button>`).join('')}</div>`:'<p class="text-gray">No uploaded documents for this session.</p>'}</div>`;document.getElementById('leaderboardPreviewModal').classList.add('active');},
    async previewDocument(cert){const title=document.getElementById('documentPreviewTitle'),body=document.getElementById('documentPreviewBody');title.textContent=cert.name;const n=cert.name.toLowerCase();if(!cert.dataUrl){body.innerHTML='<div class="cert-preview-placeholder"><i class="bi bi-file-earmark-x"></i><h4>Preview unavailable</h4><p>Re-upload this document to store its content for preview.</p></div>';}else if(n.match(/\.(png|jpe?g|gif|webp)$/))body.innerHTML=`<div class="document-viewer"><img src="${cert.dataUrl}" class="preview-image" alt="${cert.name}"></div>`;else if(n.endsWith('.pdf'))body.innerHTML=`<div class="document-viewer"><iframe src="${cert.dataUrl}" class="preview-frame" title="${cert.name}"></iframe></div>`;else if(n.endsWith('.docx')){body.innerHTML='<div class="document-viewer document-text-preview"><div class="spinner-border text-primary"></div><p>Opening certificate...</p></div>';try{const bytes=Uint8Array.from(atob(cert.dataUrl.split(',')[1]),c=>c.charCodeAt(0));const r=await mammoth.convertToHtml({arrayBuffer:bytes.buffer});body.innerHTML=`<div class="document-viewer document-text-preview">${r.value}</div>`;}catch{body.innerHTML='<div class="cert-preview-placeholder"><i class="bi bi-exclamation-circle"></i><h4>Could not render document</h4></div>';}}else body.innerHTML='<div class="cert-preview-placeholder"><i class="bi bi-file-earmark-word"></i><h4>Older .doc file</h4><p>Convert it to .docx for in-browser certificate preview.</p></div>';document.getElementById('documentPreviewModal').classList.add('active');},
};
document.addEventListener('DOMContentLoaded',()=>Leaderboard.init());
